# syntax=docker/dockerfile:1
# Talend download data container
ARG factory_base_image=alpine
ARG factory_base_image_version=3.18.0

FROM ${factory_base_image}:${factory_base_image_version} AS builder
ARG talend_manifest=talend.manifest
ARG talend_version=8.0.1
LABEL maintainer="eost@talend.com"
LABEL talend_version=${talend_version}

RUN apk add wget

# this volume directive is intentionally early in the dockerfile
# at this stage the content will be empty
# it is _required_ to provide a volume to the container when run to persist the downloaded files

#VOLUME talend


WORKDIR /talend/downloads
COPY ${talend_manifest} talend.manifest
RUN --mount=type=secret,id=talend,target=talend.credentials \
  { IFS="=" read -r property_name talend_user; IFS="=" read -r property_name talend_password; } < talend.credentials \
  && cat talend.manifest \
         | xargs -n 1 -P 2 \
             wget \
               --quiet \
               --http-user="${talend_user}" \
               --http-password="${talend_password}"
