#!/usr/bin/env bash

set -euo pipefail

source "./talend-distro.sh"

INFO_LOG=true

#talend_distro "$@"
#talend_distro build -m short.manifest "$@"
#talend_distro build "$@"
#talend_distro run "$@"
talend_distro test "$@"
