#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

if [ "${1:-}" == "-h" ]; then
    declare usage="./test [<talend_version>]"
    echo "${usage}"
    exit
fi


# parameters

declare -r talend_version="${1:-8.0.1}"


# config can be overridden by shell variables

declare -r image_name="${image_name:-talend-distro}"
declare -r tester_image="alpine"
declare -r tester_image_version="3.18.0"

docker run --name test --volumes-from "${image_name}-${talend_version}" --rm -it "${tester_image}:${tester_image_version}"
